俄文翻譯 (Translation)
ExpTechTW/TREM pull request #40
Opened 2022-08-12 17:57 UTC by Yowoapple

俄文翻譯，有任何問題請聯絡我在Discord 蘋果#8113

Русский
Ru Translation

2022-08-12 18:45 UTC, kamiya10 requested changes

2022-08-12 18:45 UTC, kamiya10 commented on TREM/page/setting.html
> +                                                                <th>Placeholder</th>
```suggestion
                                                                <th>Placeholder【<--這裡】</th>
```
這裡好像漏翻了

2022-08-12 19:49 UTC, Yowoapple commented on TREM/page/setting.html
> +                                                                <th>Placeholder</th>
Okay 已修復

2022-08-13 04:08 UTC, kamiya10 approved these changes
OK
html能改的部分應該就是這些了
其他的文本有點分散等我把它整理好就可以翻了
這個就先合併

2022-08-13 04:09 UTC, merged